### PR TITLE
Tp 11

### PR DESCRIPTION
**Pull request by saadkhan6670**
Hotel Sorting done 
Waiting for yor reviews

### CODE REVIEW

**Comment by saadkhan6670** [comment]
Sorting done 
please have a review

**Comment by khurrumqureshi** [comment]
@saadkhan6670 resolve conflicts

**Comment by saadkhan6670** [comment]
conflicts resloved

**Comment by saadkhan6670** [comment]
khurrum bhai the files this conflict is shown are not even in my branch how can i get rid of them i cant get it why its conflicting

**Pull request merged**
